version: '2.4'

services:
  jenkins:
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_controller/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml
    restart: always

  sonarqube:
    # depends_on:
    #   - jenkins
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always

  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    restart: always

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium_hub
    environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always